// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyNeo4j.model;
using System;

namespace MyNeo4j.Migrations
{
    [DbContext(typeof(Neo4jDbContext))]
    [Migration("20171027102555_initialstage")]
    partial class initialstage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyNeo4j.model.ActivitiesHappened", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("id");

                    b.ToTable("Activityhappened");
                });

            modelBuilder.Entity("MyNeo4j.model.ChecklistBacklog", b =>
                {
                    b.Property<int>("ChecklistId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChecklistName");

                    b.Property<bool>("Status");

                    b.Property<int>("TaskId");

                    b.HasKey("ChecklistId");

                    b.HasIndex("TaskId");

                    b.ToTable("Checklistbl");
                });

            modelBuilder.Entity("MyNeo4j.model.CommentLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("id");

                    b.ToTable("Commentlog");
                });

            modelBuilder.Entity("MyNeo4j.model.Master", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Department");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Organization");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Pmaster");
                });

            modelBuilder.Entity("MyNeo4j.model.ProductBacklog", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<int>("InSprintNo");

                    b.Property<int>("Priority");

                    b.Property<int>("ProjectId");

                    b.Property<bool>("Status");

                    b.Property<string>("StoryName");

                    b.HasKey("StoryId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Productbl");
                });

            modelBuilder.Entity("MyNeo4j.model.ProjectMaster", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LeaderID");

                    b.Property<string>("Name");

                    b.Property<string>("ProjectDescription");

                    b.Property<string>("TechnologyUsed");

                    b.HasKey("ProjectId");

                    b.ToTable("ProjectM");
                });

            modelBuilder.Entity("MyNeo4j.model.ProjectMember", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActAs");

                    b.Property<int>("MemberId");

                    b.Property<int>("ProjectId");

                    b.HasKey("id");

                    b.ToTable("Projectmember");
                });

            modelBuilder.Entity("MyNeo4j.model.ReleasePlanMaster", b =>
                {
                    b.Property<int>("ReleasePlanId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("ProjectId");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("ReleaseName");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("Status");

                    b.HasKey("ReleasePlanId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Releasepl");
                });

            modelBuilder.Entity("MyNeo4j.model.SignalRMaster", b =>
                {
                    b.Property<int>("SignalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConnectionId");

                    b.Property<int>("MemberId");

                    b.Property<bool>("Online");

                    b.HasKey("SignalId");

                    b.ToTable("SignalRDb");
                });

            modelBuilder.Entity("MyNeo4j.model.SocialSignupMaster", b =>
                {
                    b.Property<int>("SignId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("PhotoUrl");

                    b.HasKey("SignId");

                    b.ToTable("Socialsm");
                });

            modelBuilder.Entity("MyNeo4j.model.SprintBacklog", b =>
                {
                    b.Property<int>("SprintId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProjectId");

                    b.Property<int>("ReleasePlanId");

                    b.Property<string>("SprintGoal");

                    b.Property<string>("SprintName");

                    b.Property<DateTime>("StartDate");

                    b.Property<bool>("Status");

                    b.Property<TimeSpan>("TotalDays");

                    b.HasKey("SprintId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Sprintbl");
                });

            modelBuilder.Entity("MyNeo4j.model.TaskBacklog", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("PersonId");

                    b.Property<int>("SprintId");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("Status");

                    b.Property<string>("TaskName");

                    b.HasKey("TaskId");

                    b.HasIndex("SprintId");

                    b.ToTable("Taaskbl");
                });

            modelBuilder.Entity("MyNeo4j.model.TeamMaster", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TeamName");

                    b.HasKey("TeamId");

                    b.ToTable("Teammaster");
                });

            modelBuilder.Entity("MyNeo4j.model.TeamMember", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MemberId");

                    b.Property<int>("TeamId");

                    b.HasKey("id");

                    b.ToTable("Teammemeber");
                });

            modelBuilder.Entity("MyNeo4j.model.ChecklistBacklog", b =>
                {
                    b.HasOne("MyNeo4j.model.TaskBacklog", "TaskBacklog")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyNeo4j.model.ProductBacklog", b =>
                {
                    b.HasOne("MyNeo4j.model.ProjectMaster", "ProjectMaster")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyNeo4j.model.ReleasePlanMaster", b =>
                {
                    b.HasOne("MyNeo4j.model.ProjectMaster", "ProjectMaster")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyNeo4j.model.SprintBacklog", b =>
                {
                    b.HasOne("MyNeo4j.model.ProjectMaster", "ProjectMaster")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyNeo4j.model.TaskBacklog", b =>
                {
                    b.HasOne("MyNeo4j.model.SprintBacklog", "SprintBacklog")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
